# frontend/Dockerfile.frontend
FROM node:18-alpine

WORKDIR /app

COPY frontend/package*.json ./
RUN npm config set strict-ssl false
RUN npm install

COPY frontend/ .

RUN npm run build

RUN npm install -g serve

EXPOSE 3000

CMD ["serve", "-s", "build", "-l", "3000"]